# Generated by Django 4.2.7 on 2023-11-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='idade',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='matricula',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='telefone',
            field=models.CharField(default='+55 12 345678900', max_length=14),
        ),
    ]
